// Multi-language strings. Add a new language by extending this object
// and adding an <option> in index.html's language <select>.
const TRANSLATIONS = {
  en: {
    dir: "ltr",
    appTitle: "GeoPlace",
    appTagline: "Type a place name, get its coordinates instantly.",
    searchPlaceholder: "Enter a city, address or landmark…",
    searchButton: "Locate",
    locating: "Locating…",
    resultTitle: "Coordinates",
    latitude: "Latitude",
    longitude: "Longitude",
    placeName: "Place",
    copy: "Copy",
    copied: "Copied!",
    mapTitle: "Map",
    alternatives: "Other matches",
    noResult: "No location found. Try another name.",
    error: "Something went wrong. Please try again.",
    attribution: "Coordinates & map data © OpenStreetMap contributors",
    langLabel: "Language",
    hint: "Press Enter or tap Locate.",
  },
  zh: {
    dir: "ltr",
    appTitle: "GeoPlace 经纬度查询",
    appTagline: "输入地名，立即获取经纬度坐标。",
    searchPlaceholder: "请输入城市、地址或地标点…",
    searchButton: "查询",
    locating: "正在定位…",
    resultTitle: "坐标",
    latitude: "纬度",
    longitude: "经度",
    placeName: "地点",
    copy: "复制",
    copied: "已复制！",
    mapTitle: "地图",
    alternatives: "其他匹配结果",
    noResult: "未找到该地点，请尝试其他名称。",
    error: "出错了，请重试。",
    attribution: "坐标与地图数据 © OpenStreetMap 贡献者",
    langLabel: "语言",
    hint: "按回车键或点击“查询”。",
  },
  "zh-TW": {
    dir: "ltr",
    appTitle: "GeoPlace 經緯度查詢",
    appTagline: "輸入地名，立即取得經緯度座標。",
    searchPlaceholder: "請輸入城市、地址或地標點…",
    searchButton: "查詢",
    locating: "正在定位…",
    resultTitle: "座標",
    latitude: "緯度",
    longitude: "經度",
    placeName: "地點",
    copy: "複製",
    copied: "已複製！",
    mapTitle: "地圖",
    alternatives: "其他符合結果",
    noResult: "找不到該地點，請嘗試其他名稱。",
    error: "發生錯誤，請重試。",
    attribution: "座標與地圖資料 © OpenStreetMap 貢獻者",
    langLabel: "語言",
    hint: "按下 Enter 鍵或點擊「查詢」。",
  },
  ja: {
    dir: "ltr",
    appTitle: "GeoPlace 緯度経度検索",
    appTagline: "地名を入力するだけで、座標を即座に取得。",
    searchPlaceholder: "都市・住所・ランドマークを入力…",
    searchButton: "検索",
    locating: "検索中…",
    resultTitle: "座標",
    latitude: "緯度",
    longitude: "経度",
    placeName: "場所",
    copy: "コピー",
    copied: "コピーしました！",
    mapTitle: "地図",
    alternatives: "その他の候補",
    noResult: "場所が見つかりませんでした。別の名前をお試しください。",
    error: "エラーが発生しました。もう一度お試しください。",
    attribution: "座標・地図データ © OpenStreetMap コントリビューター",
    langLabel: "言語",
    hint: "Enter キーまたは「検索」を押してください。",
  },
  es: {
    dir: "ltr",
    appTitle: "GeoPlace",
    appTagline: "Escribe un lugar y obtén sus coordenadas al instante.",
    searchPlaceholder: "Introduce una ciudad, dirección o lugar…",
    searchButton: "Localizar",
    locating: "Localizando…",
    resultTitle: "Coordenadas",
    latitude: "Latitud",
    longitude: "Longitud",
    placeName: "Lugar",
    copy: "Copiar",
    copied: "¡Copiado!",
    mapTitle: "Mapa",
    alternatives: "Otras coincidencias",
    noResult: "No se encontró el lugar. Prueba con otro nombre.",
    error: "Algo salió mal. Inténtalo de nuevo.",
    attribution: "Coordenadas y mapa © colaboradores de OpenStreetMap",
    langLabel: "Idioma",
    hint: "Pulsa Enter o toca Localizar.",
  },
  fr: {
    dir: "ltr",
    appTitle: "GeoPlace",
    appTagline: "Saisissez un lieu, obtenez ses coordonnées instantanément.",
    searchPlaceholder: "Entrez une ville, une adresse ou un lieu…",
    searchButton: "Localiser",
    locating: "Localisation…",
    resultTitle: "Coordonnées",
    latitude: "Latitude",
    longitude: "Longitude",
    placeName: "Lieu",
    copy: "Copier",
    copied: "Copié !",
    mapTitle: "Carte",
    alternatives: "Autres correspondances",
    noResult: "Aucun lieu trouvé. Essayez un autre nom.",
    error: "Une erreur est survenue. Réessayez.",
    attribution: "Coordonnées et carte © contributeurs OpenStreetMap",
    langLabel: "Langue",
    hint: "Appuyez sur Entrée ou cliquez sur Localiser.",
  },
  ko: {
    dir: "ltr",
    appTitle: "GeoPlace 위경도 검색",
    appTagline: "장소 이름을 입력하면 좌표가 바로 표시됩니다.",
    searchPlaceholder: "도시, 주소 또는 랜드마크를 입력하세요…",
    searchButton: "찾기",
    locating: "찾는 중…",
    resultTitle: "좌표",
    latitude: "위도",
    longitude: "경도",
    placeName: "장소",
    copy: "복사",
    copied: "복사됨!",
    mapTitle: "지도",
    alternatives: "다른 결과",
    noResult: "장소를 찾지 못했습니다. 다른 이름을 시도하세요.",
    error: "문제가 발생했습니다. 다시 시도하세요.",
    attribution: "좌표 및 지도 데이터 © OpenStreetMap 기여자",
    langLabel: "언어",
    hint: "Enter 키를 누르거나 '찾기'를 탭하세요.",
  },
  de: {
    dir: "ltr",
    appTitle: "GeoPlace",
    appTagline: "Ort eingeben, Koordinaten sofort erhalten.",
    searchPlaceholder: "Stadt, Adresse oder Ort eingeben…",
    searchButton: "Suchen",
    locating: "Suchen…",
    resultTitle: "Koordinaten",
    latitude: "Breitengrad",
    longitude: "Längengrad",
    placeName: "Ort",
    copy: "Kopieren",
    copied: "Kopiert!",
    mapTitle: "Karte",
    alternatives: "Weitere Treffer",
    noResult: "Ort nicht gefunden. Versuchen Sie einen anderen Namen.",
    error: "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    attribution: "Koordinaten & Karte © OpenStreetMap Mitwirkende",
    langLabel: "Sprache",
    hint: "Enter drücken oder Suchen antippen.",
  },
  ru: {
    dir: "ltr",
    appTitle: "GeoPlace",
    appTagline: "Введите название места — координаты появятся мгновенно.",
    searchPlaceholder: "Введите город, адрес или достопримечательность…",
    searchButton: "Найти",
    locating: "Поиск…",
    resultTitle: "Координаты",
    latitude: "Широта",
    longitude: "Долгота",
    placeName: "Место",
    copy: "Копировать",
    copied: "Скопировано!",
    mapTitle: "Карта",
    alternatives: "Другие совпадения",
    noResult: "Место не найдено. Попробуйте другое название.",
    error: "Что-то пошло не так. Попробуйте ещё раз.",
    attribution: "Координаты и карта © участники OpenStreetMap",
    langLabel: "Язык",
    hint: "Нажмите Enter или кнопку «Найти».",
  },
};

// Display names for the language selector.
const LANG_NAMES = {
  en: "English",
  zh: "简体中文",
  "zh-TW": "繁體中文",
  ja: "日本語",
  ko: "한국어",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  ru: "Русский",
};
